version: '2'
services:
  web:
    build: .
    environment:
      - PORT=8080
      - RACK_ENV=development
      - DATABASE_PREFIX=trackingpixel
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - database
    ports:
     - "80:8080"
    volumes:
     - .:/home/ubuntu/tracking
  database:
    image: postgres:9.4
    ports:
      - "5433:5432"
